### PR TITLE
enhancement (welcome-message) Add welcome message and fix display styles.

### LINKED ISSUE #81: Add a landing welcome message with explanation.
The current first interaction with the application does not really introduce the user as to what the application does.

Some sort of welcoming guide explaining what the application is about would be nice!

### PR DESCRIPTION
**Pull request by oscardavidrm**
+ Added a more descriptive placeholder for the search bar. [components/search-bar/index.js]
+ Modified CSS margin attributes for Search Bar to fit better the new results counter. [components/search-bar/styles.js]
+ Added a new Welcome message card that displays whenever there are no articles to display. The card introduces the user as to what the application does and an example to start using the service. [views/search-engine/index.js, views/search-engine/styles.js]

Closes #81

### CODE REVIEW

File: app/src/views/search-engine/index.js [hunk 1]
```diff
@@ -44,7 +47,48 @@ const SearchEngine = () => {
...
+            <Typography gutterBottom variant='h5' component='h2'>
+                Motor de búsqueda - Reglamento Vial de Monterrey
+            </Typography>
+            <Typography
+              variant='body1'
+              color='textSecondary'
+              component='p'
+              className={classes.cardContent}
+            >
+                Algoritmo para realizar búsquedas optimizadas sobre los <b>reglamentos viales oficiales</b> de tu comunidad.
```
Comment (Domene99) [inline app/src/views/search-engine/index.js:68]: I'd like an english card as well to make it easier for the hiring committe or any english only reader to understand

File: app/src/views/search-engine/index.js [hunk 2]
```diff
@@ -44,7 +47,48 @@ const SearchEngine = () => {
         setLoading={setLoading}
         loading={loading}
       />
+      <Chip
+        size='small'
+        label={`${articles.length} resultados`}
+        className={classes.resultsChip}
+      />
       <ArticlesList articles={articles} />
+      {articles.length === 0 &&
```
Comment (Domene99) [inline app/src/views/search-engine/index.js:56]: If a query returns no articles the info card will be displayed?

File: app/src/views/search-engine/index.js (hunk 1 above)
Comment (ssmall) [reply app/src/views/search-engine/index.js:68]: I wouldn't worry too much about this. For users who don't speak Spanish, Chrome will automatically offer to translate the page for them.

File: app/src/views/search-engine/index.js [hunk 3]
```diff
@@ -14,6 +15,8 @@ const SearchEngine = () => {
   const [search, setSearch] = useState('')
   const debouncedSearch = useDebounce(search, 1000)
   const getArticlesQuery = useQuery(GET_ARTICLES, { variables: { search: debouncedSearch } })
+  const classes = styles()
+  const DOC_URL = 'https://www.guadalupe.gob.mx/nuevo-reglamento-de-transito-homologado/'
```
Comment (ssmall) [inline app/src/views/search-engine/index.js:19]: This is okay as a short term fix, however in the long term you and @jaimehisao should figure out how this value could be determined dynamically. Once you add more jurisdictions, it does not make sense to hardcode this URL.

File: app/src/views/search-engine/index.js (hunk 2 above)
Comment (oscardavidrm) [reply app/src/views/search-engine/index.js:56]: Yes, that's correct!

File: app/src/views/search-engine/index.js (hunk 3 above)
Comment (oscardavidrm) [reply app/src/views/search-engine/index.js:19]: Totally agree. Once having a DB where we store the documents, fetching its information is what we should be doing.
Something like:

```
const document = await fetch('/document/id');
document.URL
document.name
...
```

That way we'd achieve a more dynamic frontend. But yeah, that's something to look into.

File: app/src/views/search-engine/index.js (hunk 2 above)
Comment (Domene99) [reply app/src/views/search-engine/index.js:56]: I forgot to respond to this, but won't this be super confusing for the user

Comment (anniefu) [reply app/src/views/search-engine/index.js:56]: +1 it'd be nice to display a no results found or something so that users don't think your app is just taking forever

File: app/src/views/search-engine/index.js (hunk 1 above)
Comment (anniefu) [reply app/src/views/search-engine/index.js:68]: I actually don't think it'd be a bad idea unless it'd take a long time. Or at least to make an hideable English version that users can click on. A good portion of your audience, including the people you present to in the final STEP presentation will be primarily English speaking. 

If you choose not to include an English card, you'll want to double check all the text translates well with Google translate.

(Also, what if someone uses not-Chrome? *horrified gasp*)

File: app/src/views/search-engine/index.js (hunk 2 above)
Comment (oscardavidrm) [reply app/src/views/search-engine/index.js:56]: I actually added a small results count right below the search bar!! So yeah, you actually get some feedback in the results count.
