### PR TITLE
bugfix (article card) Set maxHeight on article cards to fix height issue.

### LINKED ISSUE #84: Preview height for article cards not constant
Preview height for article cards is now really inconsistent between article cards making some really long, I'm guessing this is due to the new unicode formatting.

### PR DESCRIPTION
**Pull request by oscardavidrm**
+ Added a `maxHeight` attribute to the card content to limit the size of all cards.

Closes #84

### CODE REVIEW

File: app/src/views/search-engine/components/articles-list/styles.js [hunk 1]
```diff
@@ -9,7 +9,8 @@ const styles = makeStyles(() => ({
   },
   cardContent: {
     whiteSpace: 'pre-wrap',
-    marginBottom: 15
+    marginBottom: 15,
+    maxHeight: '20vh'
```
Comment (ssmall) [inline app/src/views/search-engine/components/articles-list/styles.js:13]: TIL about `vh` as a CSS unit. vcool!

Comment (oscardavidrm) [reply app/src/views/search-engine/components/articles-list/styles.js:13]: Hahahaha yeah!! There are a bunch of [units in CSS](https://www.w3schools.com/cssref/css_units.asp).
